### PR TITLE
OpenCore 0.9.3 + Ventura/Sonoma Support

### PR DESCRIPTION
**Pull request by TECHNIKVERBOT**
This PR updates the EFI to the latest OC and kext releases.

### CODE REVIEW

**Review by SkyrilHD — CHANGES_REQUESTED** [review]
LGTM, however change Ext4Dxe with ext4_x64.efi (found in OcBinaryData) and since this is the Monterey branch, it does not make sense to replace AirportItlwm with a Ventura compatible one.

EDIT: I have created a Ventura branch that you can open a PR for. Imo, we can skip Monterey, since Ventura is officially support by this machine.

**Review by SkyrilHD — APPROVED** [review]

**Comment by SkyrilHD** [comment]
Ready to merge. However, I recommend testing it before merging.

**Comment by ananjaser1211** [comment]
> Ready to merge. However, I recommend testing it before merging.

was holding off from merging until i have the chance to boot Ventura, do feel free to push to a branch however. once i have the chance ill give it a go, so far it seems about right

**Comment by vedpatel765** [comment]
Hey I booted ventura using TECHNIKVERBOT:main (https://github.com/TECHNIKVERBOT/Opencore-HP-Pavilion-Gaming-15-cx0056wm) and it worked great for me! After a quick look through, the only thing that doesn't work was WiFi, which I am trying to fix (am a hackintosh beginner). I don't know whats wrong, the Kext is there and everything but the Wifi icon is greyed out and the option to turn it on in settings is greyed out too. Ethernet works fine (which is what I used during the install process; I installed Ventura from scratch because I messed up my Monterey install LOL)

**Comment by SkyrilHD** [comment]
I think the problem is according to config.plist that the wifi will only work on Monterey. You need to remove the limit.

Basically, remove the 21.9.9 from MaxKernel and WiFi should work again. https://github.com/TECHNIKVERBOT/Opencore-HP-Pavilion-Gaming-15-cx0056wm/blob/0ee4f7fbe2ba8d4767a778e0934a06e19dfd022c/EFI/OC/config.plist#L311

**Comment by vedpatel765** [comment]
Oh that worked perfectly thank you so much! You saved me a lot of time! :D

**Comment by vedpatel765** [comment]
Hello! Just a couple quick questions. Are there changes pending in this PR or is it going to be merged soon? Can I use TECHNIKVERBOT:main to boot or are there commits yet to be added?

**Comment by SkyrilHD** [comment]
> Hello! Just a couple quick questions. Are there changes pending in this PR or is it going to be merged soon? Can I use TECHNIKVERBOT:main to boot or are there commits yet to be added?

The PR should be ready but didn't merge as we don't have anyone to test if the EFI is still working without issues. If there are no issues with the EFI, it will be merged.

**Comment by ananjaser1211** [comment]
0.8.4 Was the most recent test for the EFI on my end, low on NVME storage at the moment so cant bring back the hackintosh partition.

**Comment by vedpatel765** [comment]
Oh ok! I’ll test it on my laptop and let you know how it goes :)

**Comment by vedpatel765** [comment]
Ok so I tested this efi and everything works for me so far (except me messing up my dual boot and having to mess around for a couple hours lol). The only small kink I noticed is that my keyboard does not work in the boot picker gui anymore. Any ideas why? My mouse still works for picking entries so it’s not a major problem, but I can see this being a problem when needing to press space for the extended picker for open shell and such.

**Comment by ananjaser1211** [comment]
Thank you @TECHNIKVERBOT

**Pull request merged**
